[terminal]
default_shell = "zsh"

[theme]
name = "catppuccin"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin"


# Mirror my tmux key bindings
[keys]
prefix = "ctrl+s"

split_vertical = "prefix+|" # split window right
new_tab = "prefix+t"        # new tab with <prefix>

rename_tab = "prefix+r"        # rename tab
resize_mode = "prefix+shift+r" # resize mode

[ui.toast]
delivery = "herdr"
