require 'plugins' 
require 'plugins.config.lsp'
require 'plugins.config.indent-blankline' 
require 'plugins.config.lualine'
require 'plugins.config.treesitter'
require 'plugins.config.nvim-tree'
require 'plugins.config.cmp'
require 'plugins.config.null-ls'
require 'plugins.config.git'
require 'plugins.config.toggle-term'
require 'plugins.config.telescope'
require 'plugins.config.spectre'
--require 'plugins.config.whichkey'

-- other configs that aren't plugin related
require 'options' 
require 'keymaps' 
require 'colorscheme' 
